name: Build Executables

on:
  push:
    branches:
      - main  # Lance l'action sur les pushes vers main (ou configurez une autre branche)
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows executable
        run: |
          pyinstaller --onefile interface.py
        shell: bash

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/interface.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build macOS executable
        run: |
          pyinstaller --onefile interface.py
        shell: bash

      - name: Upload macOS executable
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/interface

# name: Build Windows Executable

# on:
#   push:
#     branches:
#       - main  
#   pull_request:

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.12'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install pyinstaller

#       - name: Build executable
#         run: |
#           pyinstaller --onefile interface.py
#         shell: bash

#       - name: Upload executable
#         uses: actions/upload-artifact@v3
#         with:
#           name: executable
#           path: dist/interface.exe
